### ISSUE TITLE
forms.ChoiceField not rendering initial values

### ISSUE THREAD

**Issue by denangeles** [wagtail/wagtail-condensedinlinepanel#12]
Hello, first of all i am not a react developer, so i do not totally understand the mechanics of react. I appreciate this repo and i myself am using this in my projects.

I've noticed that when updating an entry that renders a ChoiceField (i.e a models.CharField with the 'choices' argument), it will not initialise the entry with a value.

Looking into the code, i can see the method BaseCondensedInlinePanelFormSet.to_json is generating the initial values to the template, but when react does its magic, it does not set the initial value of the ChoiceFields.

Is there a missing JS component that is required for this particular use case to function correctly?

**Comment by kaedroho** [comment]
Thanks for reporting! Some of Wagtails form widgets aren't designed to in initialised this way, and we haven't tested every single widget yet so some may be broken. I'll have a look into this soon.

**Comment by denangeles** [comment]
Appreciate you handling this, 0.3 has fixed the issues i was seeing! Good day!
