### ISSUE TITLE
Wagtail not publishing new items after saved as draft

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail-condensedinlinepanel#19]
Steps to reproduce:
 - Add ``CondensedInlinePanel`` to a Wagtail page
 - In the editor, create a new item and save as draft
 - Now publish the page
 - The item will delete itself

**Comment by kaedroho** [comment]
This seems to happen when saving the page as draft twice. It doesnt happen if the user expands the form on the second try though.

**Comment by kaedroho** [comment]
Looks like this is the issue: https://github.com/wagtail/django-modelcluster/blob/fa1e2fc3194c8676e3ae5a2beeb7de25c6d8f219/modelcluster/forms.py#L113-L120

Django modelcluster deletes items if the ID field hasn't been submitted in the form.

**Comment by kaedroho** [comment]
Fixed by #21

**Comment by linxuanmax** [comment]
hi, If I use add_child method,and then save the page, whether the page is published? If the page is unpublished,what can I do to publish the page? Looking forward to you replay!
