### ISSUE TITLE
Icons on action buttons are slightly off-centre

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail-condensedinlinepanel#25]
When using Chrome, the action button icons (and little plus icons) seem to be slightly off-centre:

![off-centre-icons](https://user-images.githubusercontent.com/7779588/31850960-660b95e6-b654-11e7-8f46-acb866836427.png)

The cause of this seems to be a style in wagtail's CSS that adds a slight right margin to icons by default.

Adding the following CSS fixed the problem for me locally:

```
.condensed-inline-panel__add-button:before,
.condensed-inline-panel__action:before {
    margin-right: 0;
}
```

**Comment by kaedroho** [comment]
Fixed by #27
