### ISSUE TITLE
Card titles are shunted rightwards slightly when a card's state changes

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail-condensedinlinepanel#26]
The following image shows the same card in different states. It seems that the already generous gap on the left of the card title increases slightly when a card has one of the following classes:

- `condensed-inline-panel__card--changed`
- `condensed-inline-panel__card--new`
- `condensed-inline-panel__card--errors`

Example:

![further-indentation-of-card-titles](https://user-images.githubusercontent.com/7779588/31851121-25a5ffde-b657-11e7-9d20-d3ecb1993d25.png)

This produces a slight shunting of the card title when the edit icon is clicked on a previously unedited card, which happens because the width of the card's left border changes from `1px` to `3px`. 

One way this can be resolved is to adjust the left padding on the card titles slightly to counteract this. Adding the following solved the issue for me locally:

```
.condensed-inline-panel__card--changed .condensed-inline-panel__card-header,
.condensed-inline-panel__card--new .condensed-inline-panel__card-header,
.condensed-inline-panel__card--errors .condensed-inline-panel__card-header {
    padding-left: calc(1.5em - 2px);
}
```

**Comment by kaedroho** [comment]
Fixed by #27
