### ISSUE TITLE
TextField support

### ISSUE THREAD

**Issue by tylermadsen** [wagtail/wagtail-condensedinlinepanel#28]
`CondensedInlinePanel` doesn't seem to pick up values from `textarea` elements currently. If there's interest in supporting `TextField`, I think a fix _could_ be simply adding `HTMLTextAreaElement` in places where `HTMLInputElement`s are also referenced, [like here](https://github.com/wagtail/wagtail-condensedinlinepanel/blob/2899598dc885c010b46b835042ae8d69743721f1/condensedinlinepanel/static/condensedinlinepanel/src/components/FormContainer.tsx#L40) for example.

Thank you for all the effort you all have put into this project! it's really great.

**Comment by kaedroho** [comment]
Fixed by #29
