### ISSUE TITLE
Missing javascript map in static

### ISSUE THREAD

**Issue by SalahAdDin** [wagtail/wagtail-condensedinlinepanel#34]
I'm testing this useful package and i got this issue in the console:
`"GET /static/condensedinlinepanel/dist/condensedinlinepanel.bundle.js.map HTTP/1.1" 404 1907`.

Why?

**Comment by kaedroho** [comment]
It's because I've not been committing that map file because it is very big and would add bloat to git checkouts over time.

We could remove the link from the bundle which would prevent that error from appearing though.

**Comment by SalahAdDin** [comment]
@kaedroho Good idea, thank you!
