### ISSUE TITLE
Wagtail 2.0 support status

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail-condensedinlinepanel#39]
As mentioned in #33, there are a few issues with the compatibility changes made so far, some of which are easily fixed, but others not so much. 

I would say I'd be happy to submit a PR for this, but I've already had a go, and it looks like it's going to take a bit of refactoring of the various edit handler classes, which is an area of wagtail I've not really been able to get my head around. I certainly don't think I'm cut out to make the necessary changes in a backwards-compatible way.

**Comment by jdavid** [comment]
Hi, is there something left to support 2.0?

Are there plans for a 0.5 release?

**Comment by kaedroho** [comment]
Wagtail 2.0 was added in #44, looks like I just forgot to close this! I'll make a release now
