### ISSUE TITLE
Is it works with decimal field?

### ISSUE THREAD

**Issue by Wladislav** [wagtail/wagtail-condensedinlinepanel#40]
wagtail 1.13.1
TypeError
Object of type 'Decimal' is not JSON serializable
c:\python36-32\Lib\json\encoder.py in default, line 180
python 3.6.4

This occur when you try to edit saved page

class ProductVariantBase(models.Model):
       product = ParentalKey(Product, related_name='variants')
       price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='variant price')

**Comment by kaedroho** [comment]
Yep, this was solved recently. See #30

**Comment by Wladislav** [comment]
So much thanks for support! but have some problem after reinstall wagtail-codensedinlinepanel. look please
(pizzaenv) C:\Pizzaproject\pizzamizza>pip uninstall wagtail-condensedinlinepanel
Uninstalling wagtail-condensedinlinepanel-0.3:
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\__init__.py
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\__pycache__\__init__.cpython-36.pyc
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\__pycache__\edit_handlers.cpython-36.pyc
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\__pycache__\wagtail_hooks.cpython-36.pyc
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\edit_handlers.py
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\dist\.gitignore
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\dist\condensedinlinepanel.bundle.js
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\dist\condensedinlinepanel.css
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\src\components\card.tsx
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\src\components\cardset.tsx
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\src\components\formcontainer.tsx
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\src\components\gap.tsx
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\src\condensedinlinepanel.tsx
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\src\state.ts
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\static\condensedinlinepanel\src\types.ts
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\templates\condensedinlinepanel\condensedinlinepanel.html
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\templates\condensedinlinepanel\condensedinlinepanel.js
  c:\pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\wagtail_hooks.py
  c:\pizzaproject\pizzaenv\lib\site-packages\wagtail_condensedinlinepanel-0.3.dist-info\description.rst
  c:\pizzaproject\pizzaenv\lib\site-packages\wagtail_condensedinlinepanel-0.3.dist-info\installer
  c:\pizzaproject\pizzaenv\lib\site-packages\wagtail_condensedinlinepanel-0.3.dist-info\metadata
  c:\pizzaproject\pizzaenv\lib\site-packages\wagtail_condensedinlinepanel-0.3.dist-info\metadata.json
  c:\pizzaproject\pizzaenv\lib\site-packages\wagtail_condensedinlinepanel-0.3.dist-info\record
  c:\pizzaproject\pizzaenv\lib\site-packages\wagtail_condensedinlinepanel-0.3.dist-info\top_level.txt
  c:\pizzaproject\pizzaenv\lib\site-packages\wagtail_condensedinlinepanel-0.3.dist-info\wheel
Proceed (y/n)? y
  Successfully uninstalled wagtail-condensedinlinepanel-0.3

(pizzaenv) C:\Pizzaproject\pizzamizza>pip install wagtail-condensedinlinepanel==0.4.1
Collecting wagtail-condensedinlinepanel==0.4.1
  Downloading wagtail_condensedinlinepanel-0.4.1-py2.py3-none-any.whl (92kB)
    100% |████████████████████████████████| 102kB 668kB/s
Requirement already satisfied: six>=1.10.0 in c:\pizzaproject\pizzaenv\lib\site-packages (from wagtail-condensedinlinepanel==0.4.1)
Installing collected packages: wagtail-condensedinlinepanel
Successfully installed wagtail-condensedinlinepanel-0.4.1

(pizzaenv) C:\Pizzaproject\pizzamizza>python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x062A4C00>
Traceback (most recent call last):
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Pizzaproject\pizzaenv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Pizzaproject\pizzamizza\longclaw\longclawproducts\models.py", line 18, in <module>
    from condensedinlinepanel.edit_handlers import CondensedInlinePanel
  File "C:\Pizzaproject\pizzaenv\lib\site-packages\condensedinlinepanel\edit_handlers.py", line 15, in <module>
    import wagtail.VERSION
ModuleNotFoundError: No module named 'wagtail.VERSION'

**Comment by kaedroho** [comment]
What version of Wagtail are you using? (needs to be at least 1.7)

**Comment by Wladislav** [comment]
wagtail 1.13.1

**Comment by kaedroho** [comment]
Ahh, sorry I must've messed up when I merged #33. I've fixed this import and released ``0.4.2``

**Comment by Wladislav** [comment]
thanks, now reinstall has done

**Comment by kaedroho** [comment]
@Wladislav is everything working for you now?

**Comment by Wladislav** [comment]
Yes, now is all right. I will tell you, if i found something wrong.

**Comment by Wladislav** [comment]
Oh, litle problem Orderable not suppurt. [video screen](https://drive.google.com/file/d/1Pct3riNCT1v7JXyuLPF6JsT55gOnaASR/view?usp=sharing)

**Comment by Wladislav** [comment]
I would like to see in the future like this [img](https://drive.google.com/file/d/1T8xkg0ZlFi8jmVOgl8LVxGYnKWBTc5_K/view?usp=sharing)

**Comment by kaedroho** [comment]
These sound like separate issues, so please create separate tickets for them
