### ISSUE TITLE
Image Not Found Failure

### ISSUE THREAD

**Issue by jhrr** [wagtail/wagtail-condensedinlinepanel#52]
Currently if an image file is not found in `media` on page load then the whole CMS is brought to a halt with `SourceImageIOError` [here](https://github.com/wagtail/wagtail/blob/master/wagtail/images/models.py#L189) rather than rendering a missing image stub.

I think the fix might be as easy as switching out [`get_rendition`](https://github.com/wagtail/wagtail-condensedinlinepanel/blob/0eb8cba5ba52b7c86f84df1156434e096b23858b/condensedinlinepanel/edit_handlers.py#L116)  with [`get_rendition_or_not_found`](https://github.com/wagtail/wagtail/blob/f0eef2fc88043ba627b89125876f1cfe53b7fc51/wagtail/images/shortcuts.py#L4)?

**Comment by kaedroho** [comment]
Fixed by #53
