### ISSUE TITLE
Wagtail 2.3 breaks it

### ISSUE THREAD

**Issue by SundialServices** [wagtail/wagtail-condensedinlinepanel#54]
`edit_handlers.py` contains a reference to `self.related` in its `on_instance_bound` method at the bottom of the file, but Wagtail 2.3's base class apparently no longer has the attribute `related`.

**Comment by williln** [comment]
Do you know when a release for this fix will happen?

**Comment by kaedroho** [comment]
2.3 is now supported in version 0.5.1 (just hit pypi!)

**Comment by williln** [comment]
Thank you!

**Comment by mnowotka** [comment]
I don't think it actually landed on pypi:

![screenshot 2018-11-20 at 09 13 55](https://user-images.githubusercontent.com/837119/48759857-c513c900-eca4-11e8-8dc9-6e43c013744c.png)

**Comment by kaedroho** [comment]
Ahh, sorry! I didn't notice the upload error. I've now pushed 0.5.2 which includes this and some other fixes.

**Comment by mnowotka** [comment]
Thanks a lot!
