### ISSUE TITLE
Any progress on this?

### ISSUE THREAD

**Issue by Adrian-Turjak** [wagtail/wagtail-condensedinlinepanel#7]
@kaedroho Hey, any luck with this? This seems fantastic and would be really useful.

Anything I can do to help?

**Comment by kaedroho** [comment]
Hey @Adrian-Turjak, thanks for offering to help!

This extension is in good working order already, I've used it on a couple of client sites and they seem quite happy with it.

I think the main issues remaining are:

 - Add documentation
 - Make it easier to define how card headers are rendered (#5) - this is a tricky one as card headers need to be calculated on the frontend so they can update as the user changes them. I'm not sure if it's possible to make it easier than it already is so maybe this can be solved with better documentation and examples.
 - Fix issue #6

**Comment by Adrian-Turjak** [comment]
Alright, may look into helping figure out #6 

Plus will dig into #5 because I'm actually using wagtailmenus, and this would be very useful for @ababic and honestly make that far nicer to use gui wise!

Can you at least do a pypi release of this just to make it easier to install?
