### ISSUE TITLE
Python 2 support?

### ISSUE THREAD

**Issue by ababic** [wagtail/wagtail-condensedinlinepanel#8]
I wondered whether you had any plans to support Python 2? I'd understand completely if you wanted to keep it to Python 3 only (what with it being a newish thing, and Django starting to lean that way).

Looking through the code, it looks like Python 2 support is intended. But there's just a couple of places where the new style `super()` is used, which trip things up. 

Adding the usual `from __future__ import absolute_import, unicode_literals` to the top of python files might also be a good step.

I don't mind submitting a pull for this. Just wanted to check out the intentions first of all.

**Comment by ababic** [comment]
Hi @kaedroho. would you accept a pull-request for this? Is it something you'd like to support?

**Comment by kaedroho** [comment]
Hey @ababic. Yes, I'd accept a PR for this!
