### ISSUE TITLE
Add LICENSE text

### ISSUE THREAD

**Issue by rjmackay** [wagtail/wagtail-condensedinlinepanel#82]
This package doesn't seem to include any license info, except in the setup.py
Can you document the license this is released under?

**Comment by kaedroho** [comment]
Thanks for reporting this! It's BSD 3 clause like Wagtail core, I'll add the text now

**Comment by kaedroho** [comment]
Added in https://github.com/wagtail/wagtail-condensedinlinepanel/commit/6f1fa58dddfc0a4320737bfcc7a5480a90f8cb86

**Comment by rjmackay** [comment]
Thank you!
